# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `redcarpet` gem.
# Please instead update this file by running `bin/tapioca gem redcarpet`.


# pkg:gem/redcarpet#lib/redcarpet/compat.rb:71
Markdown = RedcarpetCompat

# pkg:gem/redcarpet#lib/redcarpet.rb:1
module Redcarpet; end

# pkg:gem/redcarpet#lib/redcarpet.rb:1
class Redcarpet::Markdown
  # pkg:gem/redcarpet#lib/redcarpet.rb:1
  def render(_arg0); end

  # pkg:gem/redcarpet#lib/redcarpet.rb:8
  def renderer; end

  class << self
    # pkg:gem/redcarpet#lib/redcarpet.rb:1
    def new(*_arg0); end
  end
end

# pkg:gem/redcarpet#lib/redcarpet.rb:1
module Redcarpet::Render; end

# pkg:gem/redcarpet#lib/redcarpet.rb:1
class Redcarpet::Render::Base
  # pkg:gem/redcarpet#lib/redcarpet.rb:1
  def initialize; end
end

# pkg:gem/redcarpet#lib/redcarpet.rb:1
class Redcarpet::Render::HTML < ::Redcarpet::Render::Base
  # pkg:gem/redcarpet#lib/redcarpet.rb:1
  def initialize(*_arg0); end
end

# pkg:gem/redcarpet#lib/redcarpet.rb:1
class Redcarpet::Render::HTML_TOC < ::Redcarpet::Render::Base
  # pkg:gem/redcarpet#lib/redcarpet.rb:1
  def initialize(*_arg0); end
end

# A renderer object you can use to deal with users' input. It
# enables +escape_html+ and +safe_links_only+ by default.
#
# The +block_code+ callback is also overriden not to include
# the lang's class as the user can basically specify anything
# with the vanilla one.
#
# pkg:gem/redcarpet#lib/redcarpet.rb:31
class Redcarpet::Render::Safe < ::Redcarpet::Render::HTML
  # pkg:gem/redcarpet#lib/redcarpet.rb:32
  def initialize(extensions = T.unsafe(nil)); end

  # pkg:gem/redcarpet#lib/redcarpet.rb:39
  def block_code(code, lang); end

  private

  # TODO: This is far from ideal to have such method as we
  # are duplicating existing code from Houdini. This method
  # should be defined at the C level.
  #
  # pkg:gem/redcarpet#lib/redcarpet.rb:50
  def html_escape(string); end
end

# HTML + SmartyPants renderer
#
# pkg:gem/redcarpet#lib/redcarpet.rb:21
class Redcarpet::Render::SmartyHTML < ::Redcarpet::Render::HTML
  include ::Redcarpet::Render::SmartyPants
end

# SmartyPants Mixin module
#
# Implements SmartyPants.postprocess, which
# performs smartypants replacements on the HTML file,
# once it has been fully rendered.
#
# To add SmartyPants postprocessing to your custom
# renderers, just mixin the module `include SmartyPants`
#
# You can also use this as a standalone SmartyPants
# implementation.
#
# Example:
#
#   # Mixin
#   class CoolRenderer < HTML
#     include SmartyPants
#     # more code here
#   end
#
#   # Standalone
#   Redcarpet::Render::SmartyPants.render("you're")
#
# pkg:gem/redcarpet#lib/redcarpet.rb:1
module Redcarpet::Render::SmartyPants
  extend ::Redcarpet::Render::SmartyPants

  # pkg:gem/redcarpet#lib/redcarpet.rb:1
  def postprocess(_arg0); end

  class << self
    # pkg:gem/redcarpet#lib/redcarpet.rb:87
    def render(text); end
  end
end

# XHTML Renderer
#
# pkg:gem/redcarpet#lib/redcarpet.rb:14
class Redcarpet::Render::XHTML < ::Redcarpet::Render::HTML
  # pkg:gem/redcarpet#lib/redcarpet.rb:15
  def initialize(extensions = T.unsafe(nil)); end
end

# pkg:gem/redcarpet#lib/redcarpet.rb:5
Redcarpet::VERSION = T.let(T.unsafe(nil), String)

# Creates an instance of Redcarpet with the RedCloth API.
#
# pkg:gem/redcarpet#lib/redcarpet/compat.rb:2
class RedcarpetCompat
  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:5
  def initialize(text, *exts); end

  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:3
  def text; end

  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:3
  def text=(_arg0); end

  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:12
  def to_html(*_dummy); end

  private

  # Turns a list of symbols into a hash of <tt>symbol => true</tt>.
  #
  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:66
  def list_to_truthy_hash(list); end

  # Returns two hashes, the extensions and renderer options
  # given the extension list
  #
  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:59
  def parse_extensions_and_renderer_options(exts); end

  # pkg:gem/redcarpet#lib/redcarpet/compat.rb:47
  def rename_extensions(exts); end
end

# pkg:gem/redcarpet#lib/redcarpet/compat.rb:18
RedcarpetCompat::EXTENSION_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/redcarpet#lib/redcarpet/compat.rb:44
RedcarpetCompat::RENDERER_OPTIONS = T.let(T.unsafe(nil), Array)
