# Opinionated cops - see https://ruby-style-guide.shopify.dev/ for explanations
inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.1

Minitest/AssertTruthy:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 4

Minitest/RefuteFalse:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: true
  EnforcedStyle: def_self
